#server:
#  port: 8081

spring:
  application:
    name: back_end

  config:
    import: optional:file:.env[.properties]

  # Database
  datasource:
    url: jdbc:mysql://localhost:3306/lensify
    username: root
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver

  # Mail
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_NAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# JWT
security:
  jwt:
    secret-key: ${JWT_SECRET}
    expiration-time: ${JWT_EXPIRATION}

# Swagger
open:
  api:
    title: API-service document
    version: V1.0.0
    description: API for Eyewear selling
    licenseUrl: "https://example.com/license"
    licenseName: API License
    serversUrl: http://localhost:8080/
    serversDescription: Server v1

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

vnp:
  base:
    payment-url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
  tmn-code: 9A9TA5E4
  hash-secret: LJMIJZ01YLRWCTND1YCVRM2C1L56SO6V
  return-url: http://localhost:3000/vn-pay/callback